[pytest]
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
pythonpath = .
python_files = test_*.py

# 警告（PytestConfigWarning）を非表示にする設定を追加
filterwarnings =
    ignore:Unknown config option. python_paths:pytest.PytestConfigWarning