"""Add organization_id to audit logs

Revision ID: 367542c9e1a4
Revises: 6495bc5bdaec
Create Date: 2026-01-13 08:47:08.698077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '367542c9e1a4'
down_revision = '6495bc5bdaec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('audit_logs')]
    
    if 'organization_id' not in columns:
        op.add_column('audit_logs', sa.Column('organization_id', sa.Integer(), nullable=True))
        op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
        op.create_foreign_key('fk_audit_log_org_id', 'audit_logs', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('audit_logs')]
    
    if 'organization_id' in columns:
        # Check if the foreign key exists before dropping it
        fks = inspector.get_foreign_keys('audit_logs')
        fk_names = [fk['name'] for fk in fks]
        if 'fk_audit_log_org_id' in fk_names:
            op.drop_constraint('fk_audit_log_org_id', 'audit_logs', type_='foreignkey')
        
        op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
        op.drop_column('audit_logs', 'organization_id')
    # ### end Alembic commands ###
