"""Add organization_id to audit logs

Revision ID: 367542c9e1a4
Revises: 6495bc5bdaec
Create Date: 2026-01-13 08:47:08.698077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '367542c9e1a4'
down_revision = '6495bc5bdaec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'organization_id')
    # ### end Alembic commands ###
