"""enhance_organization_model

Revision ID: 5c9c827fcf7c
Revises: 367542c9e1a4
Create Date: 2026-01-13 09:33:13.822874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c9c827fcf7c'
down_revision = '367542c9e1a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('corporate_id', sa.String(length=13), nullable=True))
    op.add_column('organizations', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_organizations_corporate_id'), 'organizations', ['corporate_id'], unique=True)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_corporate_id'), table_name='organizations')
    op.drop_column('organizations', 'is_verified')
    op.drop_column('organizations', 'website')
    op.drop_column('organizations', 'corporate_id')
    # ### end Alembic commands ###
