"""enhance_organization_model

Revision ID: 5c9c827fcf7c
Revises: 367542c9e1a4
Create Date: 2026-01-13 09:33:13.822874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c9c827fcf7c'
down_revision = '367542c9e1a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('organizations')]
    indexes = [idx['name'] for idx in inspector.get_indexes('organizations')]
    
    if 'corporate_id' not in columns:
        op.add_column('organizations', sa.Column('corporate_id', sa.String(length=13), nullable=True))
        if op.f('ix_organizations_corporate_id') not in indexes:
            op.create_index(op.f('ix_organizations_corporate_id'), 'organizations', ['corporate_id'], unique=True)
            
    if 'website' not in columns:
        op.add_column('organizations', sa.Column('website', sa.String(length=255), nullable=True))
        
    if 'is_verified' not in columns:
        op.add_column('organizations', sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False))
        
    if op.f('ix_organizations_name') not in indexes:
        op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('organizations')]
    indexes = [idx['name'] for idx in inspector.get_indexes('organizations')]

    if op.f('ix_organizations_name') in indexes:
        op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
        
    if op.f('ix_organizations_corporate_id') in indexes:
        op.drop_index(op.f('ix_organizations_corporate_id'), table_name='organizations')
        
    if 'is_verified' in columns:
        op.drop_column('organizations', 'is_verified')
        
    if 'website' in columns:
        op.drop_column('organizations', 'website')
        
    if 'corporate_id' in columns:
        op.drop_column('organizations', 'corporate_id')
    # ### end Alembic commands ###
