"""Add organizations for multi-tenancy

Revision ID: 6495bc5bdaec
Revises: 4a2d3e4f5g6h
Create Date: 2026-01-13 08:45:52.524328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6495bc5bdaec'
down_revision = '4a2d3e4f5g6h'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'projects', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_todo_project'), 'todos', type_='foreignkey')
    op.add_column('users', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_column('users', 'organization_id')
    op.create_foreign_key(op.f('fk_todo_project'), 'todos', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.drop_column('projects', 'organization_id')
    # ### end Alembic commands ###
