"""Add organizations for multi-tenancy

Revision ID: 6495bc5bdaec
Revises: 4a2d3e4f5g6h
Create Date: 2026-01-13 08:45:52.524328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6495bc5bdaec'
down_revision = '4a2d3e4f5g6h'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    # Check projects table
    proj_columns = [c['name'] for c in inspector.get_columns('projects')]
    if 'organization_id' not in proj_columns:
        op.add_column('projects', sa.Column('organization_id', sa.Integer(), nullable=True))
        op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
        op.create_foreign_key('fk_projects_org_id', 'projects', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    
    # Check todos table constraint
    todos_fks = [fk['name'] for fk in inspector.get_foreign_keys('todos')]
    if 'fk_todo_project' in todos_fks:
        op.drop_constraint('fk_todo_project', 'todos', type_='foreignkey')
    elif op.f('fk_todo_project') in todos_fks:
        op.drop_constraint(op.f('fk_todo_project'), 'todos', type_='foreignkey')
        
    # Check users table
    user_columns = [c['name'] for c in inspector.get_columns('users')]
    if 'organization_id' not in user_columns:
        op.add_column('users', sa.Column('organization_id', sa.Integer(), nullable=True))
        op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
        op.create_foreign_key('fk_users_org_id', 'users', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    # Check users table
    user_columns = [c['name'] for c in inspector.get_columns('users')]
    if 'organization_id' in user_columns:
        user_fks = [fk['name'] for fk in inspector.get_foreign_keys('users')]
        if 'fk_users_org_id' in user_fks:
            op.drop_constraint('fk_users_org_id', 'users', type_='foreignkey')
        op.drop_index(op.f('ix_users_organization_id'), table_name='users')
        op.drop_column('users', 'organization_id')
        
    # Restore todos constraint
    todos_fks = [fk['name'] for fk in inspector.get_foreign_keys('todos')]
    if 'fk_todo_project' not in todos_fks and op.f('fk_todo_project') not in todos_fks:
        op.create_foreign_key('fk_todo_project', 'todos', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
        
    # Check projects table
    proj_columns = [c['name'] for c in inspector.get_columns('projects')]
    if 'organization_id' in proj_columns:
        proj_fks = [fk['name'] for fk in inspector.get_foreign_keys('projects')]
        if 'fk_projects_org_id' in proj_fks:
            op.drop_constraint('fk_projects_org_id', 'projects', type_='foreignkey')
        op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
        op.drop_column('projects', 'organization_id')
    # ### end Alembic commands ###
